# .readthedocs.yml
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

version: 2
sphinx:
  configuration: conf.py

build:
  image: latest

formats: all
python:
  version: 3.7
  install:
    - requirements: requirements.txt
    - method: pip
      path: .
      extra_requirements:
        - YAML
        - html-gen
